### ISSUE TITLE
Wont start the game automatically

### ISSUE THREAD

**Issue by LevitateGamer** [Z4ee/Pipsi-SR-Releases#10]
> Checksum of your game: F687DBFF
> Injecting Bypass.dll..
> Mapped DLL at 0000000000180000
> Mapping info at 0000000000190000
> Shell code at 00000000001A0000
> Data allocated
> Thread created at: 00000000001A0000, waiting for return...
> Bypass.dll successfully injected!
> Waiting for the game to initialize..
> Injecting Cheat.dll..
> Target process memory allocation failed (ex) 0x5
> Failed to inject Cheat.dll
> Press any key to continue . . .

This happens when I use launcher and run Star Rail manually because it wont launch Star Rail.

**Comment by xiaomohen2023** [comment]
I also find the same problem now, but there is no such issue when I fist used it...

**Comment by CYZ9421** [comment]
I'm having the same problem.
