### ISSUE TITLE
can it support multi-clienting ？

### ISSUE THREAD

**Issue by link-fgfgui** [Z4ee/Pipsi-SR-Releases#100]
hoyoverse baned multi-clienting in version 2.6. Can you lift the restriction? Thanks alot

**Comment by Z4ee** [comment]
![image](https://github.com/user-attachments/assets/a63c24cc-7884-4c6b-b18f-bc3d3c5b4b2a)

**Comment by Z4ee** [comment]
yes
![image](https://github.com/user-attachments/assets/1e6aa8e8-d635-4044-b999-d7f787c43004)
