### ISSUE TITLE
The author would like to ask you what kind of situation this is

### ISSUE THREAD

**Issue by qsnp** [Z4ee/Pipsi-SR-Releases#104]
The following error message occurs according to the normal operation before, what is the problem?
![{8V%9IDSJHH{2E AU(`T56P](https://github.com/user-attachments/assets/fc20ccb5-ca2f-474a-ba68-c6b7fe9aee31)

**Comment by luoshihang** [comment]
还没出国服版本，得等。

**Comment by qsnp** [comment]
> 还没出国服版本，得等。

好的谢谢
