### ISSUE TITLE
Battle acceleration cannot be used. After the battle is over, it will keep spinning and cannot proceed to the next step

### ISSUE THREAD

**Issue by momentdiedie** [Z4ee/Pipsi-SR-Releases#105]

**Comment by momentdiedie** [comment]
![image](https://github.com/user-attachments/assets/8cd2b018-e2a9-4561-b24d-7f50ccece50f)

**Comment by momentdiedie** [comment]
Can you solve this problem?

**Comment by Z4ee** [comment]
https://github.com/Z4ee/Pipsi-SR-Releases/releases/tag/1.1.6
