### ISSUE TITLE
`Peeking` enabled cause game crash when switching to `World` tab

### ISSUE THREAD

**Issue by tedzify** [Z4ee/Pipsi-SR-Releases#11]
Enable `Misc→Peeking`, then click `World` tab. The game will crash immediately.

**Comment by Z4ee** [comment]
> Enable `Misc→Peeking`, then click `World` tab. The game will crash immediately.

misc->config->reset or delete Pipsi-HSR.cfg

**Comment by tedzify** [comment]
> misc->config->reset or delete Pipsi-HSR.cfg

Reset and deleted `Pipsi-HSR.cfg`. Issue still occuring.

**Comment by tedzify** [comment]
https://github.com/Z4ee/Pipsi-SR-Releases/assets/99535026/c39114a9-8678-4c10-a543-d8dc6f25aae3

**Comment by Z4ee** [comment]
[fixed](https://github.com/Z4ee/Pipsi-SR-Releases/releases/tag/1.0.3)
