### ISSUE TITLE
Chinese version 1.1.9 crashes when opened

### ISSUE THREAD

**Issue by 365898744** [Z4ee/Pipsi-SR-Releases#112]

**Comment by 365898744** [comment]
Launching executable 'E:\miHoYo Launcher\games\Star Rail Game\StarRail.exe'..
Starting DLL injection for 'Bypass.dll'..
DLL 'Bypass.dll' successfully injected into the process.
Waiting for the game window to initialize..
Waiting 25000 ms for game to initialize..
Starting DLL injection for 'Cheat.dll'..
Thread creation failed 0x5.
Failed to inject DLL 'Cheat.dll'.
Failed to inject the DLL into the process.
请按任意键继续. . .
![Uploading QQ20241028-163111.png…]()

**Comment by Z4ee** [comment]
turn off the antivirus, restart your PC and try again

**Comment by 365898744** [comment]
Thank you. After turning off all the fire protection settings, the app no longer crashes. This issue didn't exist in previous versions.
