### ISSUE TITLE
Select the executable game file.. No executable file selected.

### ISSUE THREAD

**Issue by JakeEpps55** [Z4ee/Pipsi-SR-Releases#114]
I'm select the exe Star Rail, 
![image](https://github.com/user-attachments/assets/f6324b4a-0b2b-494e-8e46-27c4adc8bfb4)
![image](https://github.com/user-attachments/assets/f504f5f8-4b2d-4ff9-b987-7c7be0c06ce5)

**Comment by Z4ee** [comment]
try write the path yourself in Settings.ini 

like this
```
[Settings]
Executable=D:\Games\Star Rail Games\StarRail.exe
```
