### ISSUE TITLE
after injection, game launch always crash.

### ISSUE THREAD

**Issue by bbbrj** [Z4ee/Pipsi-SR-Releases#115]
used 1.1.9 yesterday , all was good.(thx for your effort)

but today on a new device, everytime i launch the game, it crashes after loading(just see my characters).
tried the official repair tool, nothing change.

btw, i was run this in a vm on mac, idk whether this matters.

**Comment by bbbrj** [comment]
<img width="1512" alt="1" src="https://github.com/user-attachments/assets/73df5d47-84fd-410a-bc9a-4b8810cb102b">
<img width="1512" alt="2" src="https://github.com/user-attachments/assets/42110757-ecba-4ff9-b0c4-7184c7752aa7">
<img width="872" alt="3" src="https://github.com/user-attachments/assets/b6e1b0b6-4848-4fc9-9926-64a90787891e">

**Comment by Z4ee** [comment]
https://github.com/Z4ee/Pipsi-SR-Releases/issues/112

**Comment by Z4ee** [comment]
What is written in the console?

**Comment by bbbrj** [comment]
> What is written in the Launcher`s console?

i've identified the problem. it's a game's bug.....only the new area "college" leads to the crash.
it wasn't caused by this program.

anyway, thx!!
