### ISSUE TITLE
The Chinese version cannot be used 1.2.1

### ISSUE THREAD

**Issue by momentdiedie** [Z4ee/Pipsi-SR-Releases#116]
The Chinese version cannot be used 1.2.1The Chinese version cannot be used 1.2.1The Chinese version cannot be used 1.2.1The Chinese version cannot be used 1.2.1

**Comment by Z4ee** [comment]
why?

**Comment by momentdiedie** [comment]
> 为什么？

No problem now, thank you sincerely
