### ISSUE TITLE
Battle Speed Bug

### ISSUE THREAD

**Issue by RezkyRizaldi** [Z4ee/Pipsi-SR-Releases#119]
So while I'm doing dailies when my Trailblaze Power is at 29/240 and waiting at the "Continuing for Battle" screen for the -1, I recognize the Trailblaze Power regen countdown's speed is affected by the Battle Speed. I'm not sure if it's just a visual bug or actually affecting to the real countdown timer, but I hope HoYoverse doesn't detect it as a cheat. Could you check it ASAP?

**Comment by Z4ee** [comment]
don't worry, if you don't have Risk Mode enabled, there's nothing to be concerned about
