### ISSUE TITLE
I kinda deserve it but I softlock myself in the "Onward! Cloudford" event mission...

### ISSUE THREAD

**Issue by AlvinOFsanta** [Z4ee/Pipsi-SR-Releases#12]
I absolutely deserved it...
My braindead a** very conveniently tp'ed to one of the locked areas and very conveniently solved one of the puzzles I should not have solved. Now the quest is telling me to solve the puzzle, I could only stood there and realized there is no puzzle to be solved...
I know that I can't reset missions in Star Rail, is there anything I could do to get out of this softlock?
![image](https://github.com/Z4ee/Pipsi-SR-Releases/assets/18333484/b764bd28-efc8-4099-9bb2-1a4cbe12d7cb)

**Comment by tedzify** [comment]
If re-opening the game does not solve it, then the only way to fix it is to contact Hoyo support and ask them to fix it for you.

**Comment by jaksarawut** [comment]
Have you solved this problem yet?

**Comment by AlvinOFsanta** [comment]
> Have you solved this problem yet?

No, this problem is not solved. Unfortunately, according to Hoyoverse, this problem is unresolvable because of the involvement of third-party tools, even if you ask them to fix it for you nicely. They will refuse doing anything to your account. If there isn't anything our developer can do, this issue will go on forever.
