### ISSUE TITLE
china version failded to start

### ISSUE THREAD

**Issue by zwhbuild** [Z4ee/Pipsi-SR-Releases#13]
since pipsi-sr upgrading from 1.0.2 to 1.0.3,the china version failded to start ,the console show "checksum of your game: 4E4E127F",downgrade to 1.0.2 pipsi-sr works well.
![1](https://github.com/Z4ee/Pipsi-SR-Releases/assets/20163242/b3a7316b-de8b-48d0-8fd5-4388f5a8a0a9)

**Comment by Z4ee** [comment]
> since pipsi-sr upgrading from 1.0.2 to 1.0.3,the china version failded to start ,the console show "checksum of your game: 4E4E127F",downgrade to 1.0.2 pipsi-sr works well. ![1](https://private-user-images.githubusercontent.com/20163242/318313981-b3a7316b-de8b-48d0-8fd5-4388f5a8a0a9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDg2ODIsIm5iZiI6MTcxMTk0ODM4MiwicGF0aCI6Ii8yMDE2MzI0Mi8zMTgzMTM5ODEtYjNhNzMxNmItZGU4Yi00OGQwLThmZDUtNDM4OGY1YThhMGE5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA1MTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZDFiYzdmMmVjZTc1OTEzZjAzNmM1Mzg4ODJjOWJkNGNkMjU3ODY0NGUyYWYzZDgwOWM2YmI4NmU4ZGNkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GhxM_T2r2Fp4hgfE-HXCOY4L9bNLRFXsJ2cVkx2zRuU)

just click any key
![image](https://github.com/Z4ee/Pipsi-SR-Releases/assets/113752393/d11e7745-addc-410f-a40b-edbf735839ff)
