### ISSUE TITLE
I need a program for a game adapted to Bilibili’s server

### ISSUE THREAD

**Issue by rinen0721** [Z4ee/Pipsi-SR-Releases#15]
I understand that my request might be a bit excessive, considering the number of players on the Bilibili server is not large, but I do have this need. When I try to run this program on a game on the Bilibili server, the login interface is for the Chinese server. This means I can’t use this program with the Bilibili server version of the game. I hope there is a method that can be adapted. Thanks to the author.

**Comment by Ev0lt** [comment]
It seems that neither the Chinese server nor the Bilibili server can be used. Both the Chinese server and the Bilibili server have the same source code, but the login SDK is different. I have tried using the Chinese server, but it crashes and is unstable
