### ISSUE TITLE
No insert key on my laptop.

### ISSUE THREAD

**Issue by HyakuAr** [Z4ee/Pipsi-SR-Releases#16]
I have no insert key on my laptop which mean I can't even open the gui to change the key to open it. Any way to solve that?

**Comment by BUnipendix** [comment]
using OSK to open menu and change its key

**Comment by HyakuAr** [comment]
> using OSK to open menu and change its key

Wdym by OSK?

**Comment by tedzify** [comment]
Use On-Screen Keyboard to open the menu, then change the keybinding to whatever is convenient for you.
