### ISSUE TITLE
auto talk without delay, it cannot be used

### ISSUE THREAD

**Issue by lzcasdef** [Z4ee/Pipsi-SR-Releases#24]

**Comment by YelkaCap** [comment]
fix it by binding a button to the function, then, when the dialog cutscene pops up, just hold the binded button. it worked for me so i hope it also could work for you 
![image](https://github.com/Z4ee/Pipsi-SR-Releases/assets/108367465/8c9aceaf-1420-4387-b73e-6c1b1c610b18)

**Comment by lzcasdef** [comment]
I have tried it, still cannot be used
