### ISSUE TITLE
auto talk cannot be used

### ISSUE THREAD

**Issue by Tianqi00100** [Z4ee/Pipsi-SR-Releases#26]
There is no conversation acceleration
The screen occasionally goes black after skipping a scene

**Comment by YelkaCap** [comment]
i fixed this issue by binding the button to the dialog skip func, you just need to hold the button when the dialog pops up:
![image](https://github.com/Z4ee/Pipsi-SR-Releases/assets/108367465/41cd945f-1e5f-4e27-a568-456169776195)

**Comment by w1606141925** [comment]
我试了一下不太行

> 我通过将按钮绑定到对话框 skip func 解决了这个问题，您只需要在弹出对话框时按住按钮： ![图像](https://private-user-images.githubusercontent.com/108367465/328929892-41cd945f-1e5f-4e27-a568-456169776195.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjA4MjcsIm5iZiI6MTcxNTIyMDUyNywicGF0aCI6Ii8xMDgzNjc0NjUvMzI4OTI5ODkyLTQxY2Q5NDVmLTFlNWYtNGUyNy1hNTY4LTQ1NjE2OTc3NjE5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwMjA4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2RjY2JlZmZiMjBkZDIzMmZiNGUwNDA3ODdmNzQxMGMxNTgwYjkxOGY0YzE5OTBhY2FjYjU3ODMwMWJkN2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kUAGfa4psmBCnp9vOBG-NSMMfIHIroOHFxom50ZwTM0)
