### ISSUE TITLE
stuck after defeating 2.2 trailblazer mission boss

### ISSUE THREAD

**Issue by cstevano** [Z4ee/Pipsi-SR-Releases#29]
anyone here facing an issue where you got stucked at pom-pom loading screen right after defeating the 2.2 trailblazer boss?
![photo_2024-05-09_01-00-49](https://github.com/Z4ee/Pipsi-SR-Releases/assets/119917538/6f336395-4f9a-45ea-879d-5b682c269eba)

anything i can do to fix this?

**Comment by Agonyy95** [comment]
Same issue.

**Comment by cstevano** [comment]
> Same issue, hoping for a fix in some way. Also tried to login in on my phone but the same happens...

I've tried several method such as deleting registry related to hoyoverse, updating gpu driver, even 
**Re-installing**. But nothings working.

**Comment by cstevano** [comment]
> This is also the case with my account, and the same is true for logging in on a normal device, and there is currently no other way than to contact Hoyoverse customer service![Image_1715217103549.jpg](https://private-user-images.githubusercontent.com/143149344/329096422-4891301c-57f0-47ac-bab1-a346dd889553.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMzAwMjAsIm5iZiI6MTcxNTIyOTcyMCwicGF0aCI6Ii8xNDMxNDkzNDQvMzI5MDk2NDIyLTQ4OTEzMDFjLTU3ZjAtNDdhYy1iYWIxLWEzNDZkZDg4OTU1My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwNDQyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDNhOTk3NmUzZGEzMjc0NDIxMzM2ZDMyNTU2NWM5NDRhM2E2MWRlNDU0NTVhMzhmZTI5MzBiZmI3YzI3OWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gzQRonomLddEeyFt0Ch5-d0lYLCzyA3fHAdx0pGB4Jw)

yes.i already tried to contact HSR CS but they haven't gave any respond yet

**Comment by XiyaoG** [comment]
I have more than 10 people here who have experienced the same thing as you

**Comment by cstevano** [comment]
> I have more than 10 people here who have experienced the same thing as you

Are all of them using cheats?

**Comment by shinsaw26** [comment]
Yikes, this is scary

**Comment by XiyaoG** [comment]
> > 我这里有10多个和你经历过同样事情的人
> 
> 他们都在用作弊软件吗？

Fortunately, I have not encountered such a situation.Perhaps it's because I didn't turn on the Skip CutScene feature

**Comment by cstevano** [comment]
> > > 我这里有10多个和你经历过同样事情的人
> > 
> > 
> > 他们都在用作弊软件吗？
> 
> Fortunately, I have not encountered such a situation.Perhaps it's because I didn't turn on the Skip CutScene feature

i do activate the skip button, but i'm not turning on the automatic skip cutscene

**Comment by cstevano** [comment]
![Screenshot_20240509-184431_Gmail](https://github.com/Z4ee/Pipsi-SR-Releases/assets/119917538/734e47c4-c9cf-4d4b-83f2-287cf7c8695f)
![Screenshot_20240509-184543_Honkai_ Star Rail](https://github.com/Z4ee/Pipsi-SR-Releases/assets/119917538/114ec95a-fed7-4d51-94dd-317cb3732b59)



- mihoyo responded
- game receive a minor update (<1mb)
- back in business, baby

**Comment by Agonyy95** [comment]
Yeah apparently it was a bug on their end, ggs.
