### ISSUE TITLE
Regarding Auto Talk and Auto Chat, they are not as good as the previous version.

### ISSUE THREAD

**Issue by Star6699** [Z4ee/Pipsi-SR-Releases#32]
Hello, author. After updating to the latest assistant, I found that the new versions of Auto Chat and Auto Talk are not as good as the previous version. I hope I can revert back to the previous version. Thank you very much.

**Comment by XiyaoG** [comment]
The current situation is not what the author wants. He has already provided us with an updated version very well. We look forward to the latest version fixing the current issue.
