### ISSUE TITLE
Unable to launch menu in latest version (v2.20, Global)

### ISSUE THREAD

**Issue by komikazui** [Z4ee/Pipsi-SR-Releases#33]
When launching the menu as instructed by the steps, it finds the checksum of the executable and does not launch the game at all. Am I missing something?

**Comment by XiyaoG** [comment]
If your game and script are both the latest versions, please check if your game has two "Star Rail. exe"

**Comment by XiyaoG** [comment]
能评论中文吗

**Comment by komikazui** [comment]
I do not have two Star Rail exes.
![image](https://github.com/Z4ee/Pipsi-SR-Releases/assets/69122752/efce643a-3834-489c-b4ae-b513edac64a2)
This is my game folder. Outside of the "Games" folder, only the default launcher program exists.

**Comment by komikazui** [comment]
If it helps, I've also added exclusions. But i still face the same issue.

**Comment by komikazui** [comment]
Solved! Remember to place the game folder OUTSIDE "Program FIles"!!!
