### ISSUE TITLE
About Wuthering Waves

### ISSUE THREAD

**Issue by NorthStar1226** [Z4ee/Pipsi-SR-Releases#36]
Dear Developer:
Do you have any plans to develop auxiliary tools for Wuthering Waves?

**Comment by HypnosCicero** [comment]
What kind of auxiliary tools?

**Comment by NorthStar1226** [comment]
> What kind of auxiliary tools?

It’s okay. I saw your Pipsi-WW project. It cannot be used on the Chinese server, but the international server is great. Thank you very much for your reply.

**Comment by HypnosCicero** [comment]
Dude, you got the wrong person, I don’t have the projects :joy:

**Comment by NorthStar1226** [comment]
> Dude, you got the wrong person, I don’t have the projects 😂

Sorry for my question, I got the wrong person. Have you seen similar tools?
https://github.com/Z4ee/Pipsi-WW-Releases
