### ISSUE TITLE
Getting stuck at Scorchsand Vacation side quest

### ISSUE THREAD

**Issue by tuananhcn** [Z4ee/Pipsi-SR-Releases#38]
i got stuck at Scorchsand Vacation side quest. After defeating all mobs, but nothing happen
![image](https://github.com/Z4ee/Pipsi-SR-Releases/assets/99953080/187583d1-bb0b-4964-8f33-cf1e77d428b7)

**Comment by sad0panda** [comment]
R.I.P You cant do anything about this it's soft-lock now

**Comment by sad0panda** [comment]
contract Hoyoverse only

**Comment by tuananhcn** [comment]
> contract Hoyoverse only

tks for replying. I tried but getting no luck
