### ISSUE TITLE
failed to inject cheat.dll

### ISSUE THREAD

**Issue by Username1726286** [Z4ee/Pipsi-SR-Releases#39]
Executable Path: H:\Star Rail\Games\StarRail.exe
Checksum of your game: 182CD2FF
Injecting Bypass.dll..
Mapped DLL at 0000000000180000
Mapping info at 0000000000190000
Shell code at 00000000001A0000
Data allocated
Thread created at: 00000000001A0000, waiting for return...
Bypass.dll successfully injected!
Waiting for the game to initialize..
Injecting Cheat.dll..
Target process memory allocation failed (ex) 0x5
Failed to inject Cheat.dll
Press any key to continue . . .

**Comment by SphinX2k6** [comment]
same issue here to ...\
