### ISSUE TITLE
Unable to download x64.rar file

### ISSUE THREAD

**Issue by YellowFever727** [Z4ee/Pipsi-SR-Releases#43]
It shows this instead of downloading it

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:64135f9c-201e-0012-1618-c29a85000000 Time:2024-06-19T07:19:06.8111206Z</Message>
</Error>

Hopefullly you can fix it as soon as possible thx

**Comment by newcarnivals** [comment]
Same. Right-click the x64.rar link then choose download also shows "File does not exist".
