### ISSUE TITLE
[Feature Request] Add option for “bypass only”

### ISSUE THREAD

**Issue by Eisaichen** [Z4ee/Pipsi-SR-Releases#49]
Thank you so much for the great work! 1.0.8 works perfectly on 2.3.0.
I just wondering if it is possible to add a command line argument to run with bypass only. Like the following:
```
Launcher.exe -bypass
```
My goal is to make Star Rail able to run inside my virtual machine, with no need for cheat. Therefore bypass alone would be enough for me, without loading for the cheating module may mitigate the risk of getting detected.

**Comment by ShirokoLEET** [comment]
https://github.com/Z4ee/StarRail-ACE-B just follow it

**Comment by Eisaichen** [comment]
@ShirokoLEET That is what I'm doing right now to achieve my goal. I just the injector from the old project and the `bypass.dll` from this one.
But, the old project has been archived and probably won't get further updates, so I'm considering the future.

**Comment by ShirokoLEET** [comment]
maybe the offset changed after game update.try to locate it
