### ISSUE TITLE
Stuck when injecting cheat.dll

### ISSUE THREAD

**Issue by ghost** [Z4ee/Pipsi-SR-Releases#52]
If you use Windows 11 24H2, the Launcher.exe will stuck when trying to inject the cheat.dll. could you please check this issue? 

![Screenshot 2024-07-06 151507](https://github.com/Z4ee/Pipsi-SR-Releases/assets/119917538/9e25e3df-c92b-4cfc-b0e7-a5f4aed82eb9)
![Screenshot 2024-07-06 151536](https://github.com/Z4ee/Pipsi-SR-Releases/assets/119917538/5d5ca6ba-2091-4c14-a1b5-5e3b6fef2df3)

**Comment by agastyarimbawa** [comment]
I have the same issue

**Comment by hekki24** [comment]
so is it fixed now? can I upgrade to IoT LTSC 24h2?

**Comment by hekki24** [comment]
> so is it fixed now? can I upgrade to IoT LTSC 24h2?

hello?
