### ISSUE TITLE
Getting game version not supported

### ISSUE THREAD

**Issue by YukiRainee** [Z4ee/Pipsi-SR-Releases#54]
![image](https://github.com/Z4ee/Pipsi-SR-Releases/assets/6981053/b68f0bb9-c78d-4c0a-a5ad-1d2ebdceee1e)
is the new pre-release not possible to be used right now?? I'm assuming it can but

**Comment by Z4ee** [comment]
download the latest version

https://github.com/Z4ee/Pipsi-SR-Releases/releases/tag/1.0.8
