### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hhHIKN** [Z4ee/Pipsi-SR-Releases#63]
1.Thank you for sharing your game plugin with us for free.
2.Here are some mistakes I have encountered.
There is a high probability of collapse when entering or exiting the battle.
New puzzles cannot be solved automatically.Even some previous treasure boxes and puzzles can't be used normally.
Unable to skip the conversation completely, the option will pop up.
3.It is very easy to collapse, and it will collapse many times.
4.I hope you can handle it as soon as possible. Thank you very much.

**Comment by bttqjs** [comment]
> 1.Thank you for sharing your game plugin with us for free. 2.Here are some mistakes I have encountered. There is a high probability of collapse when entering or exiting the battle. New puzzles cannot be solved automatically.Even some previous treasure boxes and puzzles can't be used normally. Unable to skip the conversation completely, the option will pop up. 3.It is very easy to collapse, and it will collapse many times. 4.I hope you can handle it as soon as possible. Thank you very much.


use alternative mode for auto talk to skip it completly.
