### ISSUE TITLE
Crash after restarting a fight in simulated worlds

### ISSUE THREAD

**Issue by ElopingDev** [Z4ee/Pipsi-SR-Releases#78]
Hello, title says it all, most of the time when trying to restart a fight after losing in Simulated World, the game will crash.

**Comment by Dramorian** [comment]
![image](https://github.com/user-attachments/assets/c5c0fece-b28d-4bef-a4d8-8170512a61ef)

get over it

**Comment by ElopingDev** [comment]
Game bug but it doesnt happen when the cheese isnt injected tho?
