### ISSUE TITLE
I can’t open the menu

### ISSUE THREAD

**Issue by RexZHD** [Z4ee/Pipsi-SR-Releases#8]
i start the cheat it opens the game but u press insert and it won’t open,why?

**Comment by hookzeds** [comment]
me too

**Comment by W4GNZ** [comment]
Had, but solved it. Literally stop anything else from hooking like MSI Afterburner and RTSS.

**Comment by dainsleifhawt** [comment]
2025 here, how do i fix this?

Invalid checksum for 'D:\Program Files\Games\HoYoPlay\games\Star Rail Games\GameAssembly.dll'.
Expected 0xD0694C7 'HOYOPLAY 2.7.0 GL', got 0xDBF671F 'UNKNOWN'.
