### ISSUE TITLE
Add Damage Multiplier and God Mode

### ISSUE THREAD

**Issue by SANSERMC** [Z4ee/Pipsi-SR-Releases#83]
Can you add damage multiplier? and god mode to the app?

like genshin impact one?

**Comment by MorishimaKureo** [comment]
Yeah i think it would be great if the cheat include god mode and damage multiplier

**Comment by Dramorian** [comment]
> Yeah i think it would be great if the cheat include god mode and damage multiplier

it's server-sided, enjoy your quick permaban xdd

**Comment by SANSERMC** [comment]
oh wait server sided? i dont know that

**Comment by SANSERMC** [comment]
> > Yeah i think it would be great if the cheat include god mode and damage multiplier
> 
> it's server-sided, enjoy your quick permaban xdd

but why genshin and zzz have those? hacks?

**Comment by sad0panda** [comment]
> > > Yeah i think it would be great if the cheat include god mode and damage multiplier
> > 
> > 
> > it's server-sided, enjoy your quick permaban xdd
> 
> but why genshin and zzz have those? hacks?

Bro did you know what server-side mean?
