### ISSUE TITLE
Virus detected - How to download?

### ISSUE THREAD

**Issue by CafeStrix** [Z4ee/Pipsi-SR-Releases#86]
Hello, I've tried all of Google Chrome, Microsoft Edge, Opera Browser all won't let me download it.

I even tried the "download dangerous file" button on google:

![Screenshot 2024-10-03 091052](https://github.com/user-attachments/assets/9acf6948-aee8-44fa-bbee-8c86445f8fa5)

But it still won't let me download it saying virus detected.

**Comment by Dramorian** [comment]
You have no braincelss left apparently since you haven't figured it out and came here to cry.
Sucks to be you, bro.

**Comment by Dramorian** [comment]
Disable Chrome security

**Comment by CafeStrix** [comment]
> Disable Chrome security

Thank you, I finally managed to get it to download.

**Comment by Garryink** [comment]
Otherwise, u can use other downloadable software
