### ISSUE TITLE
`Auto Treasure` causing soft-lock upon solving "Dream Tickers"

### ISSUE THREAD

**Issue by tedzify** [Z4ee/Pipsi-SR-Releases#9]
## Description
Upon solving its puzzle with `Auto Treasure` enabled, the game would freak out causing the UI of the game to start flickering. The player would also be unable to move or do anything. The only solution would be to disable `Auto Treasure` or restart the game with it turned off.

Here are what the "Dream Tickers" look like. They are scattered around penacony and require solving to get the rewards.
![image](https://github.com/Z4ee/Pipsi-SR-Releases/assets/99535026/38220c57-af07-4ba3-92e5-c2af0c50e580)

> [!NOTE]
> I have not tested other puzzles, so I am not certain if this behavior is the same with other puzzles that convert to a treasure chest upon completion.

**Comment by black6566516** [comment]
i have the same proprolem

**Comment by xiaomohen2023** [comment]
I used Auto Treasure & Auto Puzzle at the same time, never found this issue; however Auto Loot really has a bad effect in Penacony.

**Comment by tedzify** [comment]
> I used Auto Treasure & Auto Puzzle at the same time, never found this issue; however Auto Loot really has a bad effect in Penacony.

I think it was fixed in version 1.0.1. I just didn't close the issue because I already completed everything in penacony and couldn't test it anymore.
