### ISSUE TITLE
1.1.4 Error code 1004

### ISSUE THREAD

**Issue by momentdiedie** [Z4ee/Pipsi-SR-Releases#99]

**Comment by Z4ee** [comment]
and what is that supposed to mean?

**Comment by momentdiedie** [comment]
I can use version 1.1.3 normally, but after logging in to version 1.1.4, it prompts an error code and I can't use it. I'm giving you this feedback! However, I have already deleted the international version of the game. I'm playing the Chinese version. Looking forward to the update. Thanks!

**Comment by Z4ee** [comment]
send screenshot of the error

**Comment by momentdiedie** [comment]
I'm sorry, I have already uninstalled the international version. I only have the Chinese version. I apologize for any inconvenience caused.
